//
//  DataInitializer.swift
//  Goalscorer
//
//  Created by tichinose1 on 2019/01/06.
//  Copyright © 2019 example.com. All rights reserved.
//

import Foundation
import RealmSwift

final class DataInitializer {

    func initData() {
        let bundleURL = Bundle.main.url(forResource: "default", withExtension: "realm")!
        let storageURL = Realm.Configuration.defaultConfiguration.fileURL!
        do {
            try FileManager.default.copyItem(at: bundleURL, to: storageURL)
        } catch {
            print(error.localizedDescription)
        }
    }
}

let associations = [
    Association(name: "FIFA", regionCode: "WW", latitude: 47.381389, longitude: 8.574444,
                competitions: [Competition(name: "FIFA World Cup",
                                           topScorers: [TopScorer(season: "2018", header: "Goalscorers"),
                                                        TopScorer(season: "2014", header: "Goalscorers"),
                                                        // TODO: リンクが想定外のパターン
                                                        TopScorer(season: "2010", header: "Goalscorers"),
                                                        TopScorer(season: "2006", header: "Goalscorers"),
                                                        TopScorer(season: "2002", header: "Goalscorers"),
                                                        TopScorer(season: "1998", header: "Goalscorers"),
                                                        TopScorer(season: "1994", header: "Goalscorers"),
                                                        TopScorer(season: "1990", header: "Goalscorers"),
                                                        TopScorer(season: "1986", header: "Goalscorers"),
                                                        TopScorer(season: "1982", header: "Goalscorers"),
                                                        TopScorer(season: "1978", header: "Goalscorers"),
                                                        TopScorer(season: "1974", header: "Goalscorers"),
                                                        TopScorer(season: "1970", header: "Goalscorers"),
                                                        TopScorer(season: "1966", header: "Goalscorers"),
                                                        TopScorer(season: "1962", header: "Goalscorers"),
                                                        TopScorer(season: "1958", header: "Goalscorers"),
                                                        TopScorer(season: "1954", header: "Goalscorers"),
                                                        TopScorer(season: "1950", header: "Goalscorers"),
                                                        TopScorer(season: "1938", header: "Goalscorers"),
                                                        TopScorer(season: "1934", header: "Goalscorers"),
                                                        TopScorer(season: "1930", header: "Goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/FIFA_World_Cup_top_goalscorers#Overall_top_goalscorers")]),
                               Competition(name: "FIFA Club World Cup",
                                           topScorers: [TopScorer(season: "2018", header: "Goalscorers"),
                                                        TopScorer(season: "2017", header: "Goalscorers"),
                                                        TopScorer(season: "2016", header: "Goalscorers"),
                                                        TopScorer(season: "2015", header: "Goalscorers"),
                                                        TopScorer(season: "2014", header: "Goalscorers"),
                                                        TopScorer(season: "2013", header: "Goalscorers"),
                                                        TopScorer(season: "2012", header: "Goalscorers"),
                                                        TopScorer(season: "2011", header: "Goalscorers"),
                                                        TopScorer(season: "2010", header: "Goalscorers"),
                                                        TopScorer(season: "2009", header: "Scorers"),
                                                        TopScorer(season: "2008", header: "Scorers"),
                                                        TopScorer(season: "2007", header: "Scorers"),
                                                        TopScorer(season: "2006", header: "Goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_FIFA_Club_World_Cup_goalscorers#Overall_top_goalscorers")])],
                players: []),
    Association(name: "UEFA", regionCode: "CEU", latitude: 46.371009, longitude: 6.23103,
                competitions: [Competition(name: "UEFA Euro",
                                           topScorers: [TopScorer(season: "2016", header: "Goalscorers"),
                                                        TopScorer(season: "2012", header: "Goalscorers"),
                                                        TopScorer(season: "2008", header: "Goalscorers"),
                                                        TopScorer(season: "2004", header: "Goalscorers"),
                                                        TopScorer(season: "2000", header: "Goalscorers"),
                                                        TopScorer(season: "1996", header: "Goalscorers"),
                                                        TopScorer(season: "1992", header: "Goalscorers"),
                                                        TopScorer(season: "1988", header: "Goalscorers"),
                                                        TopScorer(season: "1984", header: "Goalscorers"),
                                                        TopScorer(season: "1980", header: "Goalscorers"),
                                                        TopScorer(season: "1976", header: "Goalscorers"),
                                                        TopScorer(season: "1972", header: "Goalscorers"),
                                                        TopScorer(season: "1968", header: "Goalscorers"),
                                                        TopScorer(season: "1964", header: "Goalscorers"),
                                                        TopScorer(season: "1960", header: "Goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_UEFA_European_Championship_goalscorers#Overall_top_goalscorers")]),
                               Competition(name: "UEFA Champions League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers"),
                                                        TopScorer(season: "2017–18", header: "Top goalscorers"),
                                                        TopScorer(season: "2016–17", header: "Top goalscorers"),
                                                        TopScorer(season: "2015–16", header: "Top goalscorers"),
                                                        TopScorer(season: "2014–15", header: "Top goalscorers"),
                                                        TopScorer(season: "2013–14", header: "Top goalscorers"),
                                                        TopScorer(season: "2012–13", header: "Top goalscorers"),
                                                        TopScorer(season: "2011–12", header: "Top goalscorers"),
                                                        TopScorer(season: "2010–11", header: "Top goalscorers"),
                                                        TopScorer(season: "2009–10", header: "Top goalscorers"),
                                                        TopScorer(season: "2008–09", header: "Top goalscorers"),
                                                        TopScorer(season: "2007–08", header: "Top goalscorers"),
                                                        TopScorer(season: "2006–07", header: "Top goalscorers"),
                                                        TopScorer(season: "2005–06", header: "Top goalscorers"),
                                                        TopScorer(season: "2004–05", header: "Top goalscorers"),
                                                        TopScorer(season: "2003–04", header: "Top goalscorers"),
                                                        TopScorer(season: "2002–03", header: "Top goalscorers"),
                                                        TopScorer(season: "2001–02", header: "Top goalscorers"),
                                                        TopScorer(season: "2000–01", header: "Top goalscorers"),
                                                        TopScorer(season: "1999–2000", header: "Top goalscorers"),
                                                        TopScorer(season: "1998–99", header: "Top goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_European_Cup_and_UEFA_Champions_League_top_scorers#All-time_top_scorers")]),
                               Competition(name: "UEFA Europa League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers"),
                                                        TopScorer(season: "2017–18", header: "Top goalscorers"),
                                                        TopScorer(season: "2016–17", header: "Top goalscorers"),
                                                        TopScorer(season: "2015–16", header: "Top goalscorers"),
                                                        TopScorer(season: "2014–15", header: "Top goalscorers"),
                                                        TopScorer(season: "2013–14", header: "Top goalscorers"),
                                                        TopScorer(season: "2012–13", header: "Top goalscorers"),
                                                        TopScorer(season: "2011–12", header: "Top goalscorers"),
                                                        TopScorer(season: "2010–11", header: "Top goalscorers"),
                                                        TopScorer(season: "2009–10", header: "Top goalscorers"),
                                                        TopScorer(season: "2008–09", header: "Top goalscorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Spain", regionCode: "ES", latitude: 40.383333, longitude: -3.716667,
                competitions: [Competition(name: "La Liga",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers"),
                                                        TopScorer(season: "2017–18", header: "Top goalscorers"),
                                                        TopScorer(season: "2016–17", header: "Top goalscorers"),
                                                        TopScorer(season: "2015–16", header: "Top goalscorers"),
                                                        TopScorer(season: "2014–15", header: "Top goalscorers"),
                                                        TopScorer(season: "2013–14", header: "Top goalscorers"),
                                                        TopScorer(season: "2012–13", header: "Top goalscorers"),
                                                        TopScorer(season: "2011–12", header: "Top goalscorers"),
                                                        TopScorer(season: "2010–11", header: "Top goalscorers"),
                                                        TopScorer(season: "2009–10", header: "Pichichi Trophy"),
                                                        TopScorer(season: "2008–09", header: "Pichichi Trophy"),
                                                        TopScorer(season: "2007–08", header: "Pichichi Trophy")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_La_Liga_top_scorers#All-time_top_scorers")])],
                players: [Player(name: "David Villa"),
                          Player(name: "Iago Aspas"),
                          Player(name: "Paco Alcácer"),
                          Player(name: "Aritz Aduriz"),
                          Player(name: "Álvaro Morata"),
                          Player(name: "Sandro Ramírez"),
                          Player(name: "Diego Costa")]),
    Association(name: "England", regionCode: "GB-ENG", latitude: 51.5, longitude: -0.116667,
                competitions: [Competition(name: "Premier League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers"),
                                                        TopScorer(season: "2017–18", header: "Top scorers"),
                                                        TopScorer(season: "2016–17", header: "Top scorers"),
                                                        TopScorer(season: "2015–16", header: "Top scorers"),
                                                        TopScorer(season: "2014–15", header: "Top scorers"),
                                                        TopScorer(season: "2013–14", header: "Top scorers"),
                                                        TopScorer(season: "2012–13", header: "Top scorers"),
                                                        TopScorer(season: "2011–12", header: "Top scorers"),
                                                        TopScorer(season: "2010–11", header: "Top scorers"),
                                                        TopScorer(season: "2009–10", header: "Top scorers"),
                                                        TopScorer(season: "2008–09", header: "Top scorers"),
                                                        TopScorer(season: "2007–08", header: "Top scorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_Premier_League_players_with_100_or_more_goals#Players")])],
                players: [Player(name: "Harry Kane"),
                          Player(name: "Wayne Rooney"),
                          Player(name: "Raheem Sterling"),
                          Player(name: "Jamie Vardy"),
                          Player(name: "Dele Alli")]),
    Association(name: "Italy", regionCode: "IT", latitude: 41.9, longitude: 12.483333,
                competitions: [Competition(name: "Serie A",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers"),
                                                        TopScorer(season: "2017–18", header: "Top goalscorers"),
                                                        TopScorer(season: "2016–17", header: "Top goalscorers"),
                                                        TopScorer(season: "2015–16", header: "Top goalscorers"),
                                                        TopScorer(season: "2014–15", header: "Top goalscorers"),
                                                        TopScorer(season: "2013–14", header: "Top scorers"),
                                                        TopScorer(season: "2012–13", header: "Top scorers"),
                                                        TopScorer(season: "2011–12", header: "Top goalscorers"),
                                                        TopScorer(season: "2010–11", header: "Top goalscorers"),
                                                        TopScorer(season: "2009–10", header: "Top goalscorers"),
                                                        TopScorer(season: "2008–09", header: "Top goalscorers"),
                                                        TopScorer(season: "2007–08", header: "Top goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_Serie_A_players_with_100_or_more_goals#List")])],
                players: [Player(name: "Ciro Immobile"),
                          Player(name: "Lorenzo Insigne"),
                          Player(name: "Mario Balotelli"),
                          Player(name: "Fabio Quagliarella"),
                          Player(name: "Andrea Belotti"),
                          Player(name: "Marco Borriello")]),
    Association(name: "Germany", regionCode: "DE", latitude: 50.116667, longitude: 8.683333,
                competitions: [Competition(name: "Bundesliga",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers"),
                                                        TopScorer(season: "2017–18", header: "Top scorers"),
                                                        TopScorer(season: "2016–17", header: "Top scorers"),
                                                        TopScorer(season: "2015–16", header: "Top goalscorers"),
                                                        TopScorer(season: "2014–15", header: "Top goalscorers"),
                                                        TopScorer(season: "2013–14", header: "Top scorers"),
                                                        TopScorer(season: "2012–13", header: "Top scorers"),
                                                        TopScorer(season: "2011–12", header: "Top scorers"),
                                                        TopScorer(season: "2010–11", header: "Top scorers"),
                                                        TopScorer(season: "2009–10", header: "Top scorers"),
                                                        TopScorer(season: "2008–09", header: "Top goalscorers"),
                                                        TopScorer(season: "2007–08", header: "Top goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/Bundesliga#Top_scorers")])],
                players: [Player(name: "Marco Reus"),
                          Player(name: "Timo Werner"),
                          Player(name: "Nils Petersen"),
                          Player(name: "Mario Gómez"),
                          Player(name: "Thomas Müller")]),
    Association(name: "France", regionCode: "FR", latitude: 48.8567, longitude: 2.3508,
                competitions: [Competition(name: "Ligue 1",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_Ligue_1_records_and_statistics#Goalscorers")])],
                players: [Player(name: "Antoine Griezmann"),
                          Player(name: "Kylian Mbappé"),
                          Player(name: "Karim Benzema"),
                          Player(name: "Wissam Ben Yedder"),
                          Player(name: "Anthony Martial"),
                          Player(name: "Alexandre Lacazette"),
                          Player(name: "Anthony Modeste (footballer, born 1988)"),
                          Player(name: "Franck Ribéry"),
                          Player(name: "Olivier Giroud")]),
    Association(name: "Russia", regionCode: "RU", latitude: 55.75, longitude: 37.616667,
                competitions: [Competition(name: "Russian Premier League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Portugal", regionCode: "PT", latitude: 38.713889, longitude: -9.139444,
                competitions: [Competition(name: "Primeira Liga",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [])],
                players: [Player(name: "Cristiano Ronaldo"),
                          Player(name: "André Silva (footballer, born 1995)")]),
    Association(name: "Belguim", regionCode: "BE", latitude: 50.85, longitude: 4.35,
                competitions: [Competition(name: "Belgian First Division A",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: [Player(name: "Romelu Lukaku"),
                          Player(name: "Eden Hazard"),
                          Player(name: "Dries Mertens")]),
    Association(name: "Ukraine", regionCode: "UA", latitude: 50.45, longitude: 30.523333,
                competitions: [Competition(name: "Ukrainian Premier League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Turkey", regionCode: "TR", latitude: 41.013611, longitude: 28.955,
                competitions: [Competition(name: "Süper Lig",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Netherlands", regionCode: "NL", latitude: 52.083333, longitude: 5.233333,
                competitions: [Competition(name: "Eredivisie",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: [Player(name: "Robin van Persie"),
                          Player(name: "Klaas-Jan Huntelaar"),
                          Player(name: "Arjen Robben")]),
    Association(name: "Austria", regionCode: "AT", latitude: 48.2, longitude: 16.366667,
                competitions: [Competition(name: "Austrian Football Bundesliga",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Poland", regionCode: "PL", latitude: 52.233333, longitude: 21.016667,
                competitions: [],
                players: [Player(name: "Robert Lewandowski"),
                          Player(name: "Krzysztof Piątek")]),
    Association(name: "Bosnia and Herzegovina", regionCode: "BA", latitude: 43.866667, longitude: 18.416667,
                competitions: [],
                players: [Player(name: "Edin Džeko"),
                          Player(name: "Vedad Ibišević")]),
    Association(name: "Wales", regionCode: "GB-WLS", latitude: 52.3, longitude: -3.6,
                competitions: [],
                players: [Player(name: "Gareth Bale")]),
    Association(name: "Sweden", regionCode: "SE", latitude: 59.35, longitude: 18,
                competitions: [],
                players: [Player(name: "Zlatan Ibrahimović")]),
    Association(name: "Ireland", regionCode: "IE", latitude: 53.344167, longitude: -6.2675,
                competitions: [],
                players: [Player(name: "Robbie Keane")]),
    Association(name: "Croatia", regionCode: "HR", latitude: 45.8, longitude: 16,
                competitions: [],
                players: [Player(name: "Andrej Kramarić"),
                          Player(name: "Mario Mandžukić")]),
    Association(name: "Israel", regionCode: "IL", latitude: 31.783333, longitude: 35.216667,
                competitions: [],
                players: [Player(name: "Moanes Dabour")]),
    Association(name: "Serbia", regionCode: "RS", latitude: 44.8, longitude: 20.466667,
                competitions: [],
                players: [Player(name: "Luka Jović")]),
    Association(name: "CONMEBOL", regionCode: "CSA", latitude: -25.260556, longitude: -57.516111,
                competitions: [Competition(name: "Copa América",
                                           topScorers: [TopScorer(season: "2016", header: "Goalscorers"),
                                                        TopScorer(season: "2015", header: "Goalscorers"),
                                                        TopScorer(season: "2011", header: "Goalscorers"),
                                                        TopScorer(season: "2007", header: "Goalscorers"),
                                                        TopScorer(season: "2004", header: "Goal scorers"),
                                                        TopScorer(season: "2001", header: "Goal scorers"),
                                                        TopScorer(season: "1999", header: "Goal scorers"),
                                                        TopScorer(season: "1997", header: "Goalscorers"),
                                                        TopScorer(season: "1995", header: "Goal scorers"),
                                                        TopScorer(season: "1993", header: "Goal scorers"),
                                                        TopScorer(season: "1991", header: "Goal scorers"),
                                                        TopScorer(season: "1989", header: "Goal scorers"),
                                                        TopScorer(season: "1987", header: "Goal scorers"),
                                                        TopScorer(season: "1983", header: "Goal scorers"),
                                                        TopScorer(season: "1979", header: "Goal scorers"),
                                                        TopScorer(season: "1975", header: "Goal scorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/Copa_Am%C3%A9rica_records_and_statistics#Goalscoring")]),
                               Competition(name: "Copa Libertadores",
                                           topScorers: [TopScorer(season: "2018", header: "Top scorers"),
                                                        TopScorer(season: "2017", header: "Top scorers"),
                                                        TopScorer(season: "2016", header: "Top goalscorers"),
                                                        TopScorer(season: "2015", header: "Top goalscorers"),
                                                        TopScorer(season: "2014", header: "Top goalscorers"),
                                                        TopScorer(season: "2013", header: "Top goalscorers"),
                                                        TopScorer(season: "2012", header: "Top goalscorers"),
                                                        TopScorer(season: "2011", header: "Top goalscorers"),
                                                        TopScorer(season: "2010", header: "Top goalscorers"),
                                                        TopScorer(season: "2009", header: "Top goalscorers"),
                                                        TopScorer(season: "2008", header: "Top goalscorers"),
                                                        TopScorer(season: "2007", header: "Top goalscorers"),
                                                        TopScorer(season: "2006", header: "Top goalscorers"),
                                                        TopScorer(season: "2005", header: "Top goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/Copa_Libertadores_records_and_statistics#All-time_top_scorers")])],
                players: []),
    Association(name: "Brazil", regionCode: "BR", latitude: -22.908333, longitude: -43.196389,
                competitions: [Competition(name: "Campeonato Brasileiro Série A",
                                           topScorers: [TopScorer(season: "2018", header: "Top scorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/Campeonato_Brasileiro_S%C3%A9rie_A_top_scorers#All-time_top_scorers")])],
                players: [Player(name: "Neymar"),
                          Player(name: "Gabriel Jesus"),
                          Player(name: "Richarlison"),
                          Player(name: "Roberto Firmino")]),
    Association(name: "Argentina", regionCode: "AR", latitude: -34.603333, longitude: -58.381667,
                competitions: [Competition(name: "Argentine Primera División",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/List_of_Argentine_Primera_Divisi%C3%B3n_top_scorers#All-time_Topscorers")])],
                players: [Player(name: "Lionel Messi"),
                          Player(name: "Sergio Agüero"),
                          Player(name: "Gonzalo Higuaín"),
                          Player(name: "Mauro Icardi"),
                          Player(name: "Carlos Tevez"),
                          Player(name: "Paulo Dybala"),
                          Player(name: "Giovanni Simeone")]),
    Association(name: "Uruguay", regionCode: "UY", latitude: -34.883611, longitude: -56.181944,
                competitions: [],
                players: [Player(name: "Luis Suárez"),
                          Player(name: "Edinson Cavani"),
                          Player(name: "Cristhian Stuani"),
                          Player(name: "Maxi Gómez")]),
    Association(name: "Colombia", regionCode: "CO", latitude: 4.583333, longitude: -74.066667,
                competitions: [],
                players: [Player(name: "Radamel Falcao")]),
    Association(name: "Chile", regionCode: "CL", latitude: -33.433333, longitude: -70.666667,
                competitions: [],
                players: [Player(name: "Alexis Sánchez")]),
    Association(name: "CONCACAF", regionCode: "CNA", latitude: 25.773, longitude: -80.138,
                competitions: [Competition(name: "CONCACAF Gold Cup",
                                           topScorers: [TopScorer(season: "2017", header: "Goalscorers"),
                                                        TopScorer(season: "2015", header: "Goalscorers"),
                                                        TopScorer(season: "2013", header: "Goalscorers"),
                                                        TopScorer(season: "2011", header: "Goalscorers"),
                                                        TopScorer(season: "2009", header: "Goalscorers"),
                                                        TopScorer(season: "2007", header: "Goalscorers"),
                                                        TopScorer(season: "2005", header: "Scorers"),
                                                        TopScorer(season: "2003", header: "Goalscorers"),
                                                        TopScorer(season: "2002", header: "Top scorers"),
                                                        TopScorer(season: "2000", header: "Top scorers"),
                                                        TopScorer(season: "1998", header: "Top scorers"),
                                                        TopScorer(season: "1996", header: "Top scorers"),
                                                        TopScorer(season: "1993", header: "Top scorers"),
                                                        TopScorer(season: "1991", header: "Goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/CONCACAF_Gold_Cup_records_and_statistics#Top_20_goal_leaders")]),
                               Competition(name: "CONCACAF Champions League",
                                           topScorers: [TopScorer(season: "2018", header: "Top goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/CONCACAF_Champions%27_Cup_and_Champions_League_records_and_statistics#All-time_top_scorers")])],
                players: []),
    Association(name: "United States", regionCode: "US", latitude: 41.836944, longitude: -87.684722,
                competitions: [Competition(name: "Major League Soccer season",
                                           topScorers: [TopScorer(season: "2018", header: "Goals")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Mexico", regionCode: "MX", latitude: 19.409444, longitude: -99.130833,
                competitions: [Competition(name: "Liga MX season",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [])],
                players: [Player(name: "Javier Hernández")]),
    Association(name: "CAF", regionCode: "CAF", latitude: 29.938126, longitude: 30.91398,
                competitions: [Competition(name: "Africa Cup of Nations",
                                           topScorers: [TopScorer(season: "2017", header: "Goalscorers"),
                                                        TopScorer(season: "2015", header: "Goalscorers"),
                                                        TopScorer(season: "2013", header: "Goalscorers"),
                                                        TopScorer(season: "2012", header: "Scorers"),
                                                        TopScorer(season: "2010", header: "Goalscorers"),
                                                        TopScorer(season: "2008", header: "Goalscorers"),
                                                        TopScorer(season: "2006", header: "Scorers"),
                                                        TopScorer(season: "2004", header: "Scorers"),
                                                        TopScorer(season: "2002", header: "Scorers"),
                                                        TopScorer(season: "2000", header: "Scorers"),
                                                        TopScorer(season: "1998", header: "Scorers"),
                                                        TopScorer(season: "1996", header: "Scorers"),
                                                        TopScorer(season: "1994", header: "Scorers"),
                                                        TopScorer(season: "1992", header: "Scorers"),
                                                        TopScorer(season: "1990", header: "Scorers"),
                                                        TopScorer(season: "1988", header: "Scorers"),
                                                        TopScorer(season: "1986", header: "Scorers"),
                                                        TopScorer(season: "1984", header: "Scorers"),
                                                        TopScorer(season: "1982", header: "Top scorers"),
                                                        TopScorer(season: "1980", header: "Scorers"),
                                                        TopScorer(season: "1978", header: "Scorers"),
                                                        TopScorer(season: "1976", header: "Scorers"),
                                                        TopScorer(season: "1974", header: "Scorers"),
                                                        TopScorer(season: "1972", header: "Goalscorers"),
                                                        TopScorer(season: "1970", header: "Goalscorers"),
                                                        TopScorer(season: "1968", header: "Goalscorers"),
                                                        TopScorer(season: "1965", header: "Scorers"),
                                                        TopScorer(season: "1963", header: "Scorers"),
                                                        TopScorer(season: "1962", header: "Scorers"),
                                                        TopScorer(season: "1959", header: "Scorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/Africa_Cup_of_Nations_records_and_statistics#Overall_top_goalscorers")]),
                               Competition(name: "CAF Champions League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top goalscorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Gabon", regionCode: "GA", latitude: 0.383333, longitude: 9.45,
                competitions: [],
                players: [Player(name: "Pierre-Emerick Aubameyang")]),
    Association(name: "Egypt", regionCode: "EG", latitude: 30.033333, longitude: 31.233333,
                competitions: [],
                players: [Player(name: "Mohamed Salah")]),
    Association(name: "Cameroon", regionCode: "CM", latitude: 3.866667, longitude: 11.516667,
                competitions: [],
                players: [Player(name: "Samuel Eto'o")]),
    Association(name: "Mali", regionCode: "ML", latitude: 12.65, longitude: -8,
                competitions: [],
                players: [Player(name: "Moussa Marega")]),
    Association(name: "Senegal", regionCode: "SN", latitude: 14.666667, longitude: -17.416667,
                competitions: [],
                players: [Player(name: "Sadio Mané")]),
    Association(name: "Algeria", regionCode: "DZ", latitude: 36.7, longitude: 3.216667,
                competitions: [],
                players: [Player(name: "Riyad Mahrez")]),
    Association(name: "OFC", regionCode: "COC", latitude: -36.840556, longitude: 174.74,
                competitions: [Competition(name: "OFC Nations Cup",
                                           topScorers: [TopScorer(season: "2016", header: "Goalscorers"),
                                                        TopScorer(season: "2012", header: "Goalscorers"),
                                                        TopScorer(season: "2008", header: "Goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/OFC_Nations_Cup_records_and_statistics#Overall_top_goalscorers")]),
                               Competition(name: "OFC Champions League",
                                           topScorers: [TopScorer(season: "2018", header: "Top goalscorers"),
                                                        TopScorer(season: "2017", header: "Top goalscorers"),
                                                        TopScorer(season: "2016", header: "Top goalscorers"),
                                                        TopScorer(season: "2014–15", header: "Top goalscorers"),
                                                        TopScorer(season: "2013–14", header: "Top goalscorers"),
                                                        TopScorer(season: "2012–13", header: "Goalscorers"),
                                                        TopScorer(season: "2011–12", header: "Goalscorers"),
                                                        TopScorer(season: "2010–11", header: "Goalscorers"),
                                                        TopScorer(season: "2009–10", header: "Topscorers"),
                                                        TopScorer(season: "2008–09", header: "Topscorers"),
                                                        TopScorer(season: "2007–08", header: "Top goal-scorers"),
                                                        TopScorer(season: "2007", header: "Top goal-scorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/Oceania_Club_Championship_and_OFC_Champions_League_records_and_statistics#All-time_top_scorers")])],
                players: []),
    Association(name: "AFC", regionCode: "CAS", latitude: 3.056296, longitude: 101.688919,
                competitions: [Competition(name: "AFC Asian Cup",
                                           topScorers: [TopScorer(season: "2019", header: "Goalscorers"),
                                                        TopScorer(season: "2015", header: "Goalscorers"),
                                                        TopScorer(season: "2011", header: "Scorers"),
                                                        TopScorer(season: "2007", header: "Goalscorers"),
                                                        TopScorer(season: "2004", header: "Goalscorers"),
                                                        TopScorer(season: "2000", header: "Goalscorers"),
                                                        TopScorer(season: "1996", header: "Goalscorers"),
                                                        TopScorer(season: "1992", header: "Goalscorers"),
                                                        TopScorer(season: "1988", header: "Goalscorers"),
                                                        TopScorer(season: "1984", header: "Goalscorers"),
                                                        TopScorer(season: "1980", header: "Goalscorers"),
                                                        TopScorer(season: "1976", header: "Goalscorers"),
                                                        TopScorer(season: "1972", header: "Goalscorers"),
                                                        TopScorer(season: "1968", header: "Goalscorers"),
                                                        TopScorer(season: "1964", header: "Scorers"),
                                                        TopScorer(season: "1960", header: "Goalscorers"),
                                                        TopScorer(season: "1956", header: "Goalscorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/AFC_Asian_Cup_records_and_statistics#Overall_top_goalscorers")]),
                               Competition(name: "AFC Champions League",
                                           topScorers: [TopScorer(season: "2018", header: "Top scorers"),
                                                        TopScorer(season: "2017", header: "Top scorers"),
                                                        TopScorer(season: "2016", header: "Top scorers"),
                                                        TopScorer(season: "2015", header: "Top scorers"),
                                                        TopScorer(season: "2014", header: "Top scorers"),
                                                        TopScorer(season: "2013", header: "Top scorers"),
                                                        TopScorer(season: "2012", header: "Top scorers"),
                                                        TopScorer(season: "2011", header: "Top scorers"),
                                                        TopScorer(season: "2010", header: "Top scorers"),
                                                        TopScorer(season: "2009", header: "Top scorers"),
                                                        TopScorer(season: "2008", header: "Top scorers"),
                                                        TopScorer(season: "2007", header: "Top scorers"),
                                                        TopScorer(season: "2006", header: "Top scorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/Asian_Club_Championship_and_AFC_Champions_League_records_and_statistics#All-time_top_goalscorers")])],
                players: []),
    Association(name: "Australia", regionCode: "AU", latitude: -33.865, longitude: 151.209444,
                competitions: [Competition(name: "A-League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Qatar", regionCode: "QA", latitude: 25.3, longitude: 51.516667,
                competitions: [Competition(name: "Qatar Stars League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "United Arab Emirates", regionCode: "AE", latitude: 25.263056, longitude: 55.297222,
                competitions: [Competition(name: "UAE Pro-League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Season statistics")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Iran", regionCode: "IR", latitude: 35.683333, longitude: 51.416667,
                competitions: [Competition(name: "Persian Gulf Pro League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "Saudi Arabia", regionCode: "SA", latitude: 24.633333, longitude: 46.716667,
                competitions: [Competition(name: "Saudi Professional League",
                                           topScorers: [TopScorer(season: "2018–19", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "China", regionCode: "CN", latitude: 39.916667, longitude: 116.383333,
                competitions: [Competition(name: "Chinese Super League",
                                           topScorers: [TopScorer(season: "2018", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: []),
    Association(name: "South Korea", regionCode: "KR", latitude: 37.55, longitude: 126.966667,
                competitions: [Competition(name: "K League 1",
                                           topScorers: [TopScorer(season: "2018", header: "Top scorers")],
                                           allTimeTopScorers: [])],
                players: [Player(name: "Son Heung-min")]),
    Association(name: "Japan", regionCode: "JP", latitude: 35.683333, longitude: 139.766667,
                competitions: [Competition(name: "J1 League",
                                           topScorers: [TopScorer(season: "2018", header: "Top scorers")],
                                           allTimeTopScorers: [AllTimeTopScorer(url: "https://en.wikipedia.org/wiki/J.League_records_and_statistics#Ranks")])],
                players: [])
]
